import { Article, Author } from '@/types'

export const mockAuthors: Partial<Author>[] = [
  {
    id: 'author-1',
    name: 'Sophea Chan',
    slug: 'sophea-chan',
    role: 'Senior Political Correspondent',
    bio: 'Sophea Chan has covered politics for over 15 years, specializing in electoral systems and parliamentary affairs.',
    avatar: { id: 'media-a1', filename: 'sophea.jpg', url: 'https://picsum.photos/seed/sophea/200/200', alt: 'Sophea Chan' } as any,
    twitter: 'sophea_pulefeed',
    email: 'sophea@pulefeed.tech',
  },
  {
    id: 'author-2',
    name: 'Dara Pich',
    slug: 'dara-pich',
    role: 'International Affairs Editor',
    bio: 'Dara Pich leads Pulefeed\'s international desk, reporting on ASEAN diplomacy and global geopolitics.',
    avatar: { id: 'media-a2', filename: 'dara.jpg', url: 'https://picsum.photos/seed/dara/200/200', alt: 'Dara Pich' } as any,
    twitter: 'dara_pulefeed',
    email: 'dara@pulefeed.tech',
  },
  {
    id: 'author-3',
    name: 'Maly Ros',
    slug: 'maly-ros',
    role: 'Data & Investigations Reporter',
    bio: 'Maly Ros leads data investigations, turning complex datasets into compelling public-interest stories.',
    avatar: { id: 'media-a3', filename: 'maly.jpg', url: 'https://picsum.photos/seed/maly/200/200', alt: 'Maly Ros' } as any,
    twitter: 'maly_pulefeed',
    email: 'maly@pulefeed.tech',
  },
]

const auth = (id: string) => mockAuthors.find((a) => a.id === id) as any

export const mockArticles: Partial<Article>[] = [
  {
    id: 'art-1',
    title: 'Parliament Votes to Extend Emergency Powers for Third Consecutive Year',
    slug: 'parliament-votes-extend-emergency-powers',
    excerpt: 'The lower house passed a resolution extending executive emergency powers by a margin of 87 votes, drawing fierce opposition from civil society groups.',
    coverImage: { url: 'https://images.unsplash.com/photo-1529107386311-07b54f597bb3?q=80&w=2000&auto=format&fit=crop', alt: 'Parliament building at night' } as any,
    author: auth('author-1'),
    status: 'published',
    isBreaking: true,
    isFeatured: true,
    language: 'all',
    publishedAt: '2026-04-12T04:00:00Z',
    readTime: 6,
    tags: [{ tag: 'parliament' }, { tag: 'emergency powers' }, { tag: 'legislation' }],
    createdAt: '2026-04-12T04:00:00Z',
    updatedAt: '2026-04-12T04:00:00Z',
  },
  {
    id: 'art-2',
    title: 'Opposition Leader Calls for Snap Election Amid Economic Crisis',
    slug: 'opposition-leader-calls-snap-election-economic-crisis',
    excerpt: 'In a strongly worded statement, the opposition leader demanded the government dissolve parliament and call for fresh elections within 90 days.',
    coverImage: { url: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?q=80&w=2000&auto=format&fit=crop', alt: 'Opposition rally with banners' } as any,
    author: auth('author-1'),
    status: 'published',
    isBreaking: true,
    isFeatured: true,
    publishedAt: '2026-04-11T10:00:00Z',
    readTime: 5,
    tags: [{ tag: 'elections' }, { tag: 'opposition' }, { tag: 'economy' }],
    createdAt: '2026-04-11T10:00:00Z',
    updatedAt: '2026-04-11T10:00:00Z',
  },
  {
    id: 'art-3',
    title: 'Foreign Minister Signs Historic Trade Deal with Regional Bloc',
    slug: 'foreign-minister-signs-historic-trade-deal-regional-bloc',
    excerpt: 'After 18 months of negotiations, the landmark agreement will eliminate tariffs on over 4,000 goods and open new corridors for regional investment.',
    coverImage: { url: 'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?q=80&w=2000&auto=format&fit=crop', alt: 'ministers signing agreement' } as any,
    author: auth('author-2'),
    status: 'published',
    isBreaking: false,
    isFeatured: true,
    publishedAt: '2026-04-10T08:30:00Z',
    readTime: 7,
    tags: [{ tag: 'trade' }, { tag: 'ASEAN' }, { tag: 'international' }],
    createdAt: '2026-04-10T08:30:00Z',
    updatedAt: '2026-04-10T08:30:00Z',
  },
  {
    id: 'art-4',
    title: 'Supreme Court Rules Against Government in Landmark Privacy Case',
    slug: 'supreme-court-rules-against-government-landmark-privacy-case',
    excerpt: 'The court\'s 6-3 ruling found that mass surveillance programs violated constitutional privacy rights, ordering an immediate suspension of data collection.',
    coverImage: { url: 'https://images.unsplash.com/photo-1589216532372-1c2a11f90e6a?q=80&w=2000&auto=format&fit=crop', alt: 'Supreme court exterior' } as any,
    author: auth('author-1'),
    status: 'published',
    isBreaking: false,
    isFeatured: false,
    publishedAt: '2026-04-09T14:00:00Z',
    readTime: 8,
    tags: [{ tag: 'supreme court' }, { tag: 'privacy' }, { tag: 'ruling' }],
    createdAt: '2026-04-09T14:00:00Z',
    updatedAt: '2026-04-09T14:00:00Z',
  },
  {
    id: 'art-5',
    title: 'Defense Budget Increases 12% as Regional Tensions Escalate',
    slug: 'defense-budget-increases-12-percent-regional-tensions',
    excerpt: 'The Ministry of National Defense released its annual budget request citing heightened maritime disputes and cross-border incidents as primary drivers.',
    coverImage: { url: 'https://images.unsplash.com/photo-1575318634028-6a0cfcb60c59?q=80&w=2000&auto=format&fit=crop', alt: 'military personnel at ceremony' } as any,
    author: auth('author-2'),
    status: 'published',
    isBreaking: false,
    isFeatured: false,
    publishedAt: '2026-04-08T09:00:00Z',
    readTime: 5,
    tags: [{ tag: 'defense' }, { tag: 'budget' }, { tag: 'security' }],
    createdAt: '2026-04-08T09:00:00Z',
    updatedAt: '2026-04-08T09:00:00Z',
  },
  {
    id: 'art-6',
    title: 'Exclusive: Inside the Coalition Negotiations That Lasted 72 Hours',
    slug: 'exclusive-inside-coalition-negotiations-72-hours',
    excerpt: 'Our reporters gained rare access to the closed-door sessions that produced the most fragile governing coalition in the nation\'s modern history.',
    coverImage: { url: 'https://images.unsplash.com/photo-1560174038-da43ac74f01b?q=80&w=2000&auto=format&fit=crop', alt: 'politicians in conference room' } as any,
    author: auth('author-1'),
    status: 'published',
    isBreaking: false,
    isFeatured: false,
    publishedAt: '2026-04-07T11:00:00Z',
    readTime: 12,
    tags: [{ tag: 'coalition' }, { tag: 'exclusive' }, { tag: 'interviews' }],
    createdAt: '2026-04-07T11:00:00Z',
    updatedAt: '2026-04-07T11:00:00Z',
  },
  {
    id: 'art-7',
    title: 'Data Analysis: How Voter Turnout Has Shifted in the Last Decade',
    slug: 'data-analysis-voter-turnout-shifted-last-decade',
    excerpt: 'A deep-dive into official election commission data reveals a 22% decline in youth voter participation since 2016, with stark urban-rural disparities.',
    coverImage: { url: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?q=80&w=2000&auto=format&fit=crop', alt: 'data visualization on screen' } as any,
    author: auth('author-3'),
    status: 'published',
    isBreaking: false,
    isFeatured: false,
    publishedAt: '2026-04-06T13:00:00Z',
    readTime: 10,
    tags: [{ tag: 'data' }, { tag: 'elections' }, { tag: 'analysis' }],
    createdAt: '2026-04-06T13:00:00Z',
    updatedAt: '2026-04-06T13:00:00Z',
  },
  {
    id: 'art-8',
    title: 'Prime Minister Reshuffles Cabinet in Surprise Midnight Announcement',
    slug: 'prime-minister-reshuffles-cabinet-surprise-midnight-announcement',
    excerpt: 'Seven ministries changed hands in the unexpected reshuffle, with three senior ministers removed and two new faces from the private sector appointed.',
    coverImage: { url: 'https://images.unsplash.com/photo-1541873676-a181ecdc5a39?q=80&w=2000&auto=format&fit=crop', alt: 'prime minister at podium' } as any,
    author: auth('author-1'),
    status: 'published',
    isBreaking: true,
    isFeatured: false,
    publishedAt: '2026-04-05T00:30:00Z',
    readTime: 6,
    tags: [{ tag: 'cabinet' }, { tag: 'prime minister' }, { tag: 'reshuffle' }],
    createdAt: '2026-04-05T00:30:00Z',
    updatedAt: '2026-04-05T00:30:00Z',
  },
]

export const mockLiveUpdates = [
  {
    id: 'live-1',
    timestamp: '2026-04-12T11:35:00Z',
    headline: 'Emergency session called for 14:00 local time',
    body: 'The Speaker has convened an emergency parliamentary session to address the crisis. All lawmakers have been recalled from recess.',
    isBreaking: true,
  },
  {
    id: 'live-2',
    timestamp: '2026-04-12T10:58:00Z',
    headline: 'Opposition walkout after procedural dispute',
    body: 'Forty-two opposition lawmakers left the chamber in protest after the ruling coalition rejected a motion to extend debate time.',
    isBreaking: false,
  },
]
