services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: pulefeed
      POSTGRES_PASSWORD: pulefeed123
      POSTGRES_DB: pulefeed
    ports:
      - '5434:5432'
    volumes:
      - pulefeed_db_data:/var/lib/postgresql/data

volumes:
  pulefeed_db_data:
